[package]
name = "kimmy-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
description = "Terminal client for KimmyDB"

[[bin]]
name = "kimmy"
path = "src/main.rs"

[dependencies]
kimmy-core.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tokio.workspace = true
reqwest.workspace = true
